--liquibase formatted sql

--changeset BelovDP:createTables
CREATE TABLE categories
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_categories PRIMARY KEY,
    deleted    boolean,
    hide       boolean,
    published  boolean,
    sort_index integer default 0      not null,
    title      character varying(255) NOT NULL,
    parent_id  bigint,
    FOREIGN KEY (parent_id) REFERENCES categories (id)
);

CREATE TABLE products
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_products PRIMARY KEY,
    deleted    boolean,
    published  boolean,
    sort_index integer default 0      not null,
    title      character varying(255) NOT NULL
);

CREATE TABLE products_categories
(
    category_id bigint not null,
    product_id  bigint not null,
    PRIMARY KEY (category_id, product_id),
    FOREIGN KEY (category_id) REFERENCES categories (id),
    FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE images
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_images PRIMARY KEY,
    image      oid NOT NULL,
    product_id bigint,
    FOREIGN KEY (product_id) REFERENCES products (id)
);