spring:
  application:
    name: gateway-service
server:
  port: 8086
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka-service.server.hostname:localhost}:${eureka-service.server.port:8084}/eureka/
gateway:
  cors: http://localhost:9000