spring:
  application:
    name: file-service
  profiles:
    active: ${file-service.project.profile:prod}
  datasource:
    url: ${products.db.url:jdbc:postgresql://localhost:5433/file_service}
    username: ${file-service.db.username:postgres}
    password: ${file-service.db.password:owner}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/main.xml
    contexts: prod
    drop-first: false
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  data:
    rest:
      basePath: /
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${file-service.keycloak.cert:http://localhost:8080/auth/realms/shop/protocol/openid-connect/certs}
server:
  port: 8088

file-service:
  dir: "./file-service/demo"
  no-image: ${file-service.dir}/no_image.jpg

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka-service.server.hostname:localhost}:${eureka-service.server.port:8084}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,logfile
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: demo
  liquibase:
    contexts: demo
    drop-first: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false