server:
  port: 8081

spring:
  data:
    rest:
      basePath: /

keycloak:
  realm: shop
  auth-server-url: http://localhost:8080/auth
  resource: shop-app
  credentials:
    secret: WBdsIy3SVkffSULcv7TuvCLYd6KsQJOI
  use-resource-role-mappings: true
  bearer-only: true

logging:
  level:
    org:
      springframework:
        security: DEBUG