server:
  port: 8081

spring:
  data:
    rest:
      basePath: /
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_REALM_CERT_URL:http://localhost:8080/auth/realms/shop/protocol/openid-connect/certs}