--liquibase formatted sql

--changeset BelovDP:createTables
CREATE TABLE orders
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_orders PRIMARY KEY,
    created  timestamp    not null,
    email    varchar(256),
    phone    varchar(20)  not null,
    note     varchar(512),
    address  varchar(512) not null,
    user_id  varchar(128),
    username varchar(128) not null
);

CREATE TABLE order_items
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_products PRIMARY KEY,
    order_id   bigint                 not null,
    product_id bigint                 not null,
    title      character varying(255) not null,
    price      decimal default '0.0'  not null,
    count      int                    not null,
    FOREIGN KEY (order_id) REFERENCES orders (id)
);