spring:
  profiles:
    active: ${products.project.profile:prod}
  datasource:
    url: ${products.db.url:jdbc:postgresql://localhost:5433/product_catalog}
    username: ${products.db.username:postgres}
    password: ${products.db.password:owner}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/main.xml
    contexts: prod
    drop-first: false
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  data:
    rest:
      basePath: /
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${products.keycloak.cert:http://localhost:8080/auth/realms/shop/protocol/openid-connect/certs}
server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: demo
  liquibase:
    contexts: demo
    drop-first: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true